# Generated by Django 3.2.3 on 2021-10-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('Phone', models.CharField(max_length=13)),
                ('cartid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.cart')),
            ],
        ),
    ]
